language: csharp
mono: none
dotnet: 2.1.503
install:
- dotnet restore
script:
- dotnet test
- dotnet build -c Release
- dotnet publish -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push Cimpress.Stereotype/bin/Release/*.nupkg  -s https://api.nuget.org/v3/index.json
    -k $NUGET_API_KEY || echo "The version is there, skipping ..."
  on:
    branch: master
env:
  global:
    secure: fMTIrTdcUL8H/v4LMeGBtDnWPyTN1ev+SVm9f8AjFaS8vIe25+QRSt4DRF/Ix7GIpf1rif9IS+gumST8gS5J+9NNGi0KhHXGsFG5T9HFaqVBMDr/c2roTzNPnIdlLWwkOmaAdCX18UjpqnfjPMI0zlUh5mmxqbgCjxnkHCrDZB694DIT6RgFNW4sq3zck/uUErDsyeTLcmAV1RfZPSgl3gPqoaBji+8LcgefaPB9yyX90Rt6d504yKtCsXgJHxiJWSQ/ZR+eqUwizkVnsvR3hO2gO9vVJBEqNTnqRt3IdTDXMhOczkDNAafSNRUTcCxpDjBpkdXijmHwF4rCyUH0wtY/rluBgJ6uV4RljHBCzJELarhYczQtJF4TZAmGug8mItZeNXEP5+bET9jhvLmAad63Zs5p8ScNx3eDa4k0IQ9ZjKqFmcD3DwLQjKhN+HtX+BnE50T8/g9M6DNPJB+eI71WalB09Ap4ccGwCM5Lja1/LQziiBab/Xircc/yoM3BpsTTy3ND1fez9MSn72n03i1nu7OClOudt/ARsQdqdk0jbEBZKW6ITOZyFCl/Fgc03F5CGK0ZE3YP0//JD4f6sQjIee1gNRLnTkL0v3S3RGXCh/lWqufIqHdPURQI0gM4/8BjxxUyOJCGAX/zw+bitRkkoNbG38hJHATkWay9pQE=
